sudo: required

services:
    - docker

before_install:
    - mkdir -p client/src/vendor

    - git clone https://github.com/toggle-corp/react-store.git client/src/vendor/react-store
    - git --git-dir=client/src/vendor/react-store/.git --no-pager show --pretty=fuller --quiet
    - cp client/src/vendor/react-store/stylesheets/_user-imports-sample.scss client/src/vendor/react-store/stylesheets/_user-imports.scss

    - git clone https://github.com/toggle-corp/ravl.git client/src/vendor/ravl
    - git --git-dir=client/src/vendor/ravl/.git --no-pager show --pretty=fuller --quiet

    - touch .env
    - docker pull devtc/humanitarian-analytics:latest
    - docker build --cache-from devtc/humanitarian-analytics:latest --tag devtc/humanitarian-analytics:latest .

before_script:
    - docker-compose up -d
    - echo 'Before test script'

script:
    - echo 'Test script'

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push devtc/humanitarian-analytics:latest
